### ISSUE TITLE
Do I have to enter a keychain value everytime when I connect wifi?

### ISSUE THREAD

**Issue by you6878** [mrodalgaard/alfred-network-workflow#11]
<img width="605" alt="Screen Shot 2019-11-26 at 1 28 04 AM" src="https://user-images.githubusercontent.com/23183710/69558812-3b4fb780-0fec-11ea-9f98-3dba020ce320.png">
<img width="546" alt="Screen Shot 2019-11-26 at 1 23 52 AM" src="https://user-images.githubusercontent.com/23183710/69558633-e1e78880-0feb-11ea-807b-da42c0704f6b.png">

Thank you. I'm glad I'm using it.
Do I have to enter a keychain value everytime when I connect wifi?
Can't I enter a keychain value automatically?

**Comment by jpuris** [comment]
+1 can reproduce.

**Comment by mrodalgaard** [comment]
Hi,

The problem is that to join an access point from the terminal / bash you need the wifi password (using `networksetup -setairportnetwork `). And to get the wifi password of a known access point you need the administration permissions. The application is actually fetching the wifi password from your keychain once you give it the rights to do so. See https://github.com/mrodalgaard/alfred-network-workflow/blob/master/src/ap.sh#L13 which is causing the popup you are showing in your issue.

There is however a workaround shortly described by `forgetfuljames` at https://superuser.com/a/1046481/439307 and in more details by `Allan Odgaard` at  https://macromates.com/blog/2006/keychain-access-from-shell/ . To summarise; you can add the `security` application as an allowed application to the specific wifi password in your keychain. Thereby `security` is allowed to fetch the wifi password as mentioned above without prompting for administration permissions.

If you think this will be helpful for others, I will add instructions to the README.

**Comment by mrodalgaard** [comment]
For now I will note this in the README and link to the above quick fix. I do not want this Alfred extension to be responsible for storing the users access point passwords.
