### ISSUE TITLE
WiFiList command in network workflow not listing all the available WiFi names

### ISSUE THREAD

**Issue by skamal1808** [mrodalgaard/alfred-network-workflow#18]
I am using your network alfred workflow on macOS 12 Monterey. Everything is working fine except the wifilist command. It’s listing the wifi but no AP names are shown. I am attaching the screenshot for better understanding 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/70901662/141946023-69afa0a9-0d30-4238-a796-429aebd08e61.png">
>

**Comment by mrodalgaard** [comment]
I see the same behaviour on Monterey. The reason is that Apple changed the `airport --scan` command, which is used for scanning for access points. sudo is needed for BSSIDs to be returned, which is used in parsing the individual access points. If you are comfortable in the terminal try running below commands and post the output here: 

`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport  --scan`

`sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport  --scan`

**Comment by skamal1808** [comment]
here is the output after running the commands
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/70901662/142396295-defd6b83-7bf4-44c6-a475-848600844174.png">

**Comment by mrodalgaard** [comment]
Hi @skamal1808, would you mind downloading and installing the artifact (Network.alfredworkflow, 551 KB, version 1.5) from https://github.com/mrodalgaard/alfred-network-workflow/actions/runs/1487815293 and test if that fixes your issue?

**Comment by skamal1808** [comment]
Yes this works. Thanks!!

**Comment by cdpath** [comment]
@mrodalgaard 
hi, I tested `1487815293` as well, it can list Wi-Fi names. However, whenever I switched an access point, it asked me for keychain access, is there any way to bypass it?

**Comment by mrodalgaard** [comment]
Great with more testing before release. I will make an official 1.5 release soon.

@cdpath; I assume you mean selecting a WiFi name from the `wifilist` list and wanting to connect to that access point when you say "switching an access point...". This is unfortunately a known limitation of this workflow caused by MacOS requiring login to extract the password from the keychain.

It is mentioned in the README:

> WIFI / Access Point changes requires your keychain password which is a known limitation. See [HERE](https://github.com/mrodalgaard/alfred-network-workflow/issues/11#issuecomment-559252188).
